[*] --> PowerSW_OFF

state PowerSW_OFF {
  [*] --> Standby
  Standby --> PowerSW_ON : PowerSWがONになる
}

state PowerSW_ON {
  state RightTurn {
    [*] --> Dark
    Dark --> RightTurn : 光センサーが黒いライン上にある
    RightTurn --> Bright : 光センサーがラインを外れる
    Bright --> LeftTurn : 光センサーが黒いライン上に戻る
  }

  state LeftTurn {
    [*] --> Bright
    Bright --> LeftTurn : 光センサーがラインを外れる
    LeftTurn --> Dark : 光センサーが黒いライン上に戻る
    Dark --> RightTurn : 光センサーがラインを外れる
  }

  RightTurn --> LeftTurn : 光センサーがラインを外れる
  LeftTurn --> RightTurn : 光センサーが黒いライン上にある
  RightTurn --> PowerSW_OFF : PowerSWがOFFになる
  LeftTurn --> PowerSW_OFF : PowerSWがOFFになる
}
