@startuml 出張申請 課題
left to right direction
actor 申請者 #DffDDD;line:black;line.bold;
actor 承認者 #aDDDDD;line:black;line.bold;
actor 経理担当者 #DDDffD;line:black;line.bold;
actor 交通費精算システム #D55DDD;line:black;line.bold;
rectangle 出張申請システム {
usecase 出張申請を登録する
usecase 出張申請を申請する
usecase 出張申請を承認する 
usecase 出張申請を却下する
usecase 出張申請を差し戻す
usecase 出張申請を確認する
}
申請者 --> 出張申請を登録する
申請者 --> 出張申請を申請する
承認者 --> 出張申請を承認する
承認者 --> 出張申請を却下する
承認者 --> 出張申請を差し戻す
承認者 --> 出張申請を確認する
経理担当者 --> 出張申請を確認する
出張申請を登録する <-- 交通費精算システム

@enduml