@startuml
start
: ユーザ名を入力する;
: パスワードを入力する;
if (認証成功?) then(yes)
    : 予約をおこなう;
else (no)
   repeat
        : ユーザ名を再入力する;
        : パスワードを再入力する;
        if (認証成功?) then(yes)
            : 予約をおこなう;
        else (no)
            : ユーザとパスワードを再入力する;
        endif
    repeat while (認証成功?ではない?)
endif

stop


@enduml
