@startuml ホテル予約
hide footbox
participant "controller:データ更新コントローラ" as controller
participant "hotel:ホテル" as hotel
participant ":予約" as reservation


activate controller
    controller -> hotel : 1:予約操作を呼び出す()
activate hotel
    create reservation
    hotel ->  reservation : 1.1:作成()
    
    hotel -> reservation : 1.2:予約登録操作を呼び出す()
    hotel <<-- reservation : 予約登録操作
    deactivate reservation

    controller <<-- hotel: 予約操作
deactivate hotel

deactivate controller
@enduml