@startuml

class ホテル {
    -部屋   
}

class 利用者 {
    -名前
    -住所
    -電話番号
}

class 部屋 {
    -タイプ
    -価格
    -  キャンペーン価格
}

class 予約 {
    -チェックイン日
    -滞在時間
    -値段
}

ホテル *-- 部屋 : 部屋数
利用者 o-- 部屋 : 予約済み
ホテル *-- 利用者 : 会員
予約 o-- 利用者 : 予約する

@enduml
