@startuml 演習3-4
    left to right direction
    object "<u>車リスト:車</u>" as car1{
        -車種
    }

    object "車リスト:車" as car2{
        -車種
    }

    object "タイヤリスト:タイヤ" as taiya1{
        -種類=オールシーズンタイヤ
        -メーカー
        -サイズ
        -価格
    }

    object "タイヤリスト:タイヤ" as taiya2{
        -種類=スタッドレスタイヤ
        -メーカー
        -サイズ
        -価格
    }

    car1 -- taiya1
    car1 -- taiya2
    car2 -- taiya1
@enduml