@startuml ステートマシン
' left to right direction
[*] -right-> メニュー
メニュー --> 予約と確認 :予約と確認ボタンを押す
予約と確認 --> あなたの順番 :確認ボタンを押す
予約と確認 --> あなたの順番 :登録ボタンを押す
予約と確認 --> メニュー :取り消しボタンを押す
あなたの順番 --> メニュー :メニューボタンを押す
メニュー -down-> 今の順番 :今の順番ボタンを押す
今の順番 -down-> メニュー :メニューボタンを押す
メニュー -right-> [*] 
@enduml