@startuml

[*] --> 電源SW_OFF

state 電源SW_OFF {
  [*] --> 待機
  待機 --> 電源SW_ON : 電源SWがONになる
}

state 電源SW_ON {
  state 右旋回 {
    [*] --> 暗い
    暗い --> 右旋回 : 光センサーが黒いライン上にある
    右旋回 --> 明るい : 光センサーがラインを外れる
    明るい --> 左旋回 : 光センサーが黒いライン上に戻る
  }

  state 左旋回 {
    [*] --> 明るい
    明るい --> 左旋回 : 光センサーがラインを外れる
    左旋回 --> 暗い : 光センサーが黒いライン上に戻る
    暗い --> 右旋回 : 光センサーがラインを外れる
  }

  右旋回 --> 左旋回 : 光センサーがラインを外れる
  左旋回 --> 右旋回 : 光センサーが黒いライン上にある
  右旋回 --> 電源SW_OFF : 電源SWがOFFになる
  左旋回 --> 電源SW_OFF : 電源SWがOFFになる
}

@enduml