@startuml

class 医師 {
    -医師ID: int
    -名前: str
    -所属医局: 医局
    +診察する(患者)
    +診察記録を作成する(患者)
}

class 医局 {
    -医局ID: int
    -名前: str
}

class 患者 {
    -患者ID: int
    -名前: str
    -担当医: 医師
    +診察を受ける()
}

class 診察記録 {
    -診察ID: int
    -診察内容: str
}

医師 *-- 患者 : 診察する
医師 *-- 診察記録 : 診察記録を作成する
患者 "1" *-- "1" 医師 : 担当医
医師 "1" -- "1" 医局 : 所属医局

@enduml